/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:9e12069e-cc88-4895-9245-c0d93e4623ce",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_3T6I4Kd21",
    "aws_user_pools_web_client_id": "5l2ernfe2isnb45arf0t4o2vlm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ywec7wzhsjbevdzigjqltuea2e.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2girlhrgn5hhdmgd5cosqooiiu",
    "aws_user_files_s3_bucket": "amplifyapp6ad25e8b520745f1a85c8d869a11b333140125-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
